version: "3.9"

services:
  server:
    container_name: shopify-backend-challenge-server
    links:
      - database
    build: ./server
    env_file:
      - server/.env.production
    ports:
      - "3000:3000"
  client:
    container_name: shopify-backend-challenge-client
    build: ./client
    env_file:
      - client/.env
    ports:
      - "4000:3000"
  database:
    container_name: shopify-backend-challenge-database
    image: postgres:14.1
    restart: always
    env_file: server/.env.production
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database:
    driver: local
